title: "KCSIE BLOG"
SEOTitle: KCSIE BLOG
description: ""
url: 
baseurl: ""
author: "KCSIE"
paginate: 5
paginate_path: "/blog/page:num/"

theme: jekyll-theme-mdui

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor